import { expect } from "chai";
import { Board } from "../src/Board.js";
import { describe, test } from "vitest";
import { Block } from "./Doubles/Block.js";

describe("A board represented as a string", () => {
  test("can be loaded with a 10x6 size", () => {
    const board = Board.loadBoard(
      `....T.....
       ....TT....
       ....T.....
       ..........
       ..........
       ..........`
    );

    expect(board.toString()).to.equalShape(
      `....T.....
       ....TT....
       ....T.....
       ..........
       ..........
       ..........`
    );
  });

  test("can be loaded with a 6x4 size", () => {
    const board = Board.loadBoard(
      `....T.
       ....TT
       ....T.
       ......`
    );

    expect(board.toString()).to.equalShape(
      `....T.
       ....TT
       ....T.
       ......`
    );
  });

  test("can drop a new block", () => {
    const board = Board.loadBoard(
      `..........
       ..........
       ..........
       ....T.....
       ....TT....
       ....T.....`
    );

    board.drop(new Block("X"));

    expect(board.toString()).to.equalShape(
      `....X.....
       ..........
       ..........
       ....T.....
       ....TT....
       ....T.....`
    );
  });

  test("can be loaded on level 5", () => {
    const board = Board.loadBoard(
      `....T.....
       ....TT....
       ....T.....
       ..........
       ..........
       ..........`,
      5
    );

    expect(board.toString()).to.equalShape(
      `....T.....
       ....TT....
       ....T.....
       ..........
       ..........
       ..........`
    );

    expect(board.level).to.equal(5);
  });
});
