import { expect } from "chai";
import { Board } from "../src/Board.js";
import { describe, test } from "vitest";

describe("A board represented as a string", () => {
  test("can be loaded", () => {
    const board = Board.loadBoard(`....T.....
    ....TT....
    ....T.....
    ..........
    ..........
    ..........`);

    expect(board.toString()).to.equalShape(
      `....T.....
       ....TT....
       ....T.....
       ..........
       ..........
       ..........`
    );
  });
});
